version: 1.0.{build}
image: Ubuntu

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm install

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - pnpm lint
  - pnpm build

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verboseejs_version
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки
  - npm run test

test_script:
  - npm run lint && npm test  # скрипт тестирования