jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" > ~/.git-credentials
          git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages || git clone --single-branch --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          cp -r ../dist/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages --force
